### ISSUE TITLE
Add So What? to the Data Types discussion

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-sql#13]
I'd suggest facilitating a conversation about why this is important. We should have some people who are familiar with the data warehouse in the class who might be able to speak to some of this:
+ Certain functions only work with specific data types
+ Have to explicitly cast from one type to another to use a function
+ May need to clean data (ex string dates -> timestamps)

**Comment by datapolitan** [comment]
@ebrelsford what do you think about [mentioning casts](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-2017)? To be honest, the process is more involved in SQL Server than Postgres, so maybe we let it go, but it might be good to at least resource them with the concept and some links to more information.

**Comment by ebrelsford** [comment]
Agreed that we need a *So What?* here.

I hadn't thought about including casts. Maybe we mention the idea and link to an example to plant the seed.
