### ISSUE TITLE
Add short exercise after data types

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-sql#15]
Maybe something for them to identify what data types there is in the table we're working with. Just to reinforce learning.

**Comment by datapolitan** [comment]
The goal is to get them aware of data types, know how to identify the data types they're working with, and why knowing data types is important. It would be great to have them try something that fails because of a data type mismatch, but that's probably asking too much.

**Comment by ebrelsford** [comment]
I rearranged a little so we could use a `WHERE` clause. Now we can use `YEAR()`, for example, to get the year out of a date field.
