### ISSUE TITLE
Process Map review

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-sql#16]
@ebrelsford Unless you're thinking of doing an exercise with the material, I wouldn't cover it just to check the box. I'd like this to be more integrated into what they're doing. Maybe after lunch they can go through the process to ideate their project with a facilitated exercise. That would buy us more time in the morning to introduce content. Does that make sense?

**Comment by ebrelsford** [comment]
That makes sense, I can work it into post-lunch. I was considering talking there about documentation (thinking about your process so you can write down the steps) but either way later should work well.
