### ISSUE TITLE
Add Joins Exercise

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-sql#18]
This may be tricky because I think both classes are struggling with this exercise of combining data sets. Maybe work with @lizdumont and @myarish to figure this one out, but ideally we give them something simple enough to clearly teach the concepts but still in the context of the data we're working with.

**Comment by datapolitan** [comment]
@ebrelsford any more need to be done for this?

**Comment by ebrelsford** [comment]
Good point--no, I think we're set on this now.
