### ISSUE TITLE
Exercise 1: loading data with SQL in Excel

### ISSUE THREAD

**Issue by ebrelsford** [Datapolitan-Training/parks-advanced-analysis-sql#3]
Needs:
 * database connection info
 * useful table
 * something to do with it in Excel once it's there

**Comment by datapolitan** [comment]
If this is complicated, we can also use an AWS instance as a sandbox for an intro exercise.

**Comment by ebrelsford** [comment]
I agree. I think it will be good to have an instance as a backup either way.

**Comment by datapolitan** [comment]
@ebrelsford This looks great. Should I ask about a small table we can load this way so we're not waiting the 15 mins (or longer) for Daily Tasks to load but don't need to get into SQL?

**Comment by datapolitan** [comment]
@ebrelsford And I have issue #11 to get a standby instance ready in case we need to use it

**Comment by ebrelsford** [comment]
@datapolitan A small table would be excellent so we don't have to get into `TOP` just to load some data.

**Comment by datapolitan** [comment]
@ebrelsford emailed the client for a recommendation. I'll let you know what they say.

**Comment by datapolitan** [comment]
@ebrelsford Just emailed a reminder to IPM for comment

**Comment by datapolitan** [comment]
This is still dangling. I'm going to shift to pre-delivery since this is on the client.

**Comment by neiljohnthompson** [comment]
@datapolitan @ebrelsford just sent the small table via email and thought that I commented here (although my comment is not showing up at the moment). 

In case it did not register for some reason: 

Just sent calendar extract from the data warehouse. This is a pretty innocuous dataset that provides reference for each day from 1-1-2015 to 6-30-2020, including where a date falls within both fiscal and calendar years (number of day, week, quarter, year). There is unfortunately no data dictionary for this dataset (yet), please let me know if you require one for this exercise. 

The path to the table is [DWH].[dbo].[tbl_ref_calendar].

**Comment by ebrelsford** [comment]
Thanks @neiljohnthompson that'll work for us.
