### ISSUE TITLE
Describe the intended result of running YEAR() query 

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-sql#36]
@ebrelsford can you please describe the result for the query [we're asking them to do here](http://training.datapolitan.com/parks-advanced-analysis-sql/#157) so I can put it in the presenter notes?

```sql
SELECT * FROM tbl_dailytasks WHERE YEAR(date_worked)=2019
```

**Comment by ebrelsford** [comment]
The idea was to emphasize the importance of data types (this wouldn't work on a text column) and that there are functions to help you modify columns so you can ask more specific questions of the data.

I'm open to other functions if you think it would be better!

Also considering the size of this table it may make more sense to select a summary of the data for 2019--maybe the count?

**Comment by datapolitan** [comment]
I think this works just fine. We can also add this as a separate column:

```sql
SELECT TOP 10 
   *,
   YEAR(date_worked) AS year_worked 
FROM tbl_dailytasks 
WHERE YEAR(date_worked)=2019
```
