### ISSUE TITLE
Fuller discussion of Joins?

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-sql#37]
@ebrelsford Do we introduce them to [the full range of Joins](https://commons.wikimedia.org/wiki/File:SQL_Joins.svg)? I wouldn't do it until we've done an actual join but I'm sure it's going to come up.

**Comment by ebrelsford** [comment]
@datapolitan I'm open to that. How would you feel about an appendix at the end of the slides with more details, similar to the way there are lists of functions at the end of the Python slides?
