### ISSUE TITLE
Exercise 2: applied SQL

### ISSUE THREAD

**Issue by ebrelsford** [Datapolitan-Training/parks-advanced-analysis-sql#4]
Needs:
 * database connection info (presumably same as from #3)
 * useful table (presumably same as from #3)
 * do the same as we did in Excel, but this time using SQL:
   * sort
   * filter
   * aggregate

**Comment by datapolitan** [comment]
@ebrelsford We can buy some time by folding the Excel I recap into this section, in other words, do the 5 data analytics tasks review, then talk about how we do this in SQL for the first three in this exercise. Does that make sense? That might help you pack more into the A Block (before first break) and help the class move along better.

**Comment by datapolitan** [comment]
Space for them to share their queries would be helpful. I don't know how we do this. Having everyone present their SQL could take too much time, but maybe working in pairs/small groups and sharing what they come up with would be useful as a mini code review
