### ISSUE TITLE
Add Database to Workbook

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-sql#45]
Server: `data.nycdpr.parks.nycnet`
Database: `DWH`

**Comment by datapolitan** [comment]
@dennisrim is there any reason we can't do this? I want to make sure we're not exposing anything sensitive

**Comment by dennisrim** [comment]
@datapolitan Nope, you are perfectly fine to add the database link to the workbook!

**Comment by datapolitan** [comment]
Thanks @dennisrim for confirming

**Comment by datapolitan** [comment]
Send example to IPM for review

**Comment by ebrelsford** [comment]
Added Database: `DWH` to workbook.
