### ISSUE TITLE
Exercise 3: SQL project

### ISSUE THREAD

**Issue by ebrelsford** [Datapolitan-Training/parks-advanced-analysis-sql#5]
Groups work through a project using SQL to import data and visualize it. Groups present their work.

Needs:
 * database connection info (as in #3 and #4)
 * useful tables (#3, #4)
 * groups should work together to come up with projects
 * groups should present work

**Comment by datapolitan** [comment]
@ebrelsford You have a "Final Exercise" and then a "Your Turn". What is your thinking here? The final exercise should probably be final.

**Comment by ebrelsford** [comment]
Just a labeling issue, thanks for pointing it out!
