### ISSUE TITLE
Beef up JOINs discussion

### ISSUE THREAD

**Issue by datapolitan** [Datapolitan-Training/parks-advanced-analysis-sql#62]
Maybe the Venn diagram, but edited down to the more simpler joins.

As per [student feedback](https://datastudio.google.com/s/lqoofFmIsNo)

**Comment by datapolitan** [comment]
I'm happy to find some other visualization than the Venn @ebrelsford if you have some ideas. I want to respect your inclination away from this.

**Comment by ebrelsford** [comment]
Open to the Venn diagrams, too, but maybe we could also include a less abstract version along these lines:

![image](https://user-images.githubusercontent.com/375002/60181674-b835f580-97f0-11e9-81bc-bc0e695f8a87.png)

([via](https://academy.vertabelo.com/blog/illustrated-guide-sql-outer-join/))

I also think it could be nice to concretely show a short excerpt of the actual tables and which rows join and which don't.

**Comment by ebrelsford** [comment]
Or

![](https://pbs.twimg.com/media/EFfT2ugW4AA9Wa2?format=jpg&name=medium) via [Julia Evans](https://twitter.com/b0rk/status/1177642768484712449)

**Comment by ebrelsford** [comment]
@datapolitan How would we feel about including the above image with attribution?
